### ISSUE TITLE
Create social media graphics (for Twitter and LinkedIn)

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/open-leadership-assessment#8]
We'll need to create and share a set of images we can use to promote the assessment on launch and beyond.

**Comment by HeidiHVL** [comment]
Adding graphics to a pull request @semioticrobotic

**Comment by semioticrobotic** [comment]
Nice work, @HeidiHVL! The graphics look great. I took an additional step to rename and reorganize the collection so it's all in the `promotional-resources` folder and a little easier to locate.

**Comment by semioticrobotic** [comment]
Since everything is now uploaded and [in a folder](https://github.com/open-organization/open-leadership-assessment/tree/main/promotional-resources), I think we're good to close.
